[workspace]
name = "conda2pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[environments]

[feature]

[dependencies]
python = ">=3.6"
pyyaml = "*"
toml = "*"

[tasks]
conda2pixi = "python conda2pixi.py"
